### ISSUE TITLE
グループチャットで反応しない問題

### ISSUE THREAD

**Issue by mtdtks** [kamera25/hubot-cybozulive#2]
こんにちは
とても素晴らしいツールです。正に欲しいと思っておりました。ありがとうございます。
1対1のチャットでは正常に作動しているのですが、グループチャットのルームIDを指定した時に反応しなくなります。
やはり、チャットPULLが無いのと、新着APIから抜き出している関係上仕方がないのでしょうか。
ちょっとcoffeescript弄ってみたのですが、私の知識不足で…ヒントだけでもいただけると助かります。
- 環境
  - windows8.1 64bit
  - heroku(旧Dyno)
- 1対1チャットのルームIDを指定
  pingでpongが帰ってくる
- グループチャットのルームIDを指定し、再起動  
  pingを打つが反応なし
- ルームIDを1対1のチャットルームに書き換えると即座に反応が返ってくる

よろしくお願いします。

**Comment by kamera25** [comment]
@mtdtks さん
バグ報告ありがとうございます。そう言って頂けると開発者としてとても嬉しいです。

このバグの原因ですが、テーマチャットIDの取得が正しくできていませんでした。
 [96aa25](https://github.com/kamera25/hubot-cybozulive/commit/96aa259aae07c791603d85e98e8c3f6254e313f2) のコミットでバグ修正を行いました。

また気を付けて頂きたい事があります。それはHubotが書き込むチャットルームに **事前に何かの
メッセージを書いてください。**(READMEに追記しておきました。)

(本アダプタは最新情報を使って取得します。何もメッセージが書かれてないとHubotのサイボウズ
アカウント側で最新情報として取得できないためです。)

npmに最新版(0.0.4a)をアップロードしましたので、ダウンロードしてお使いください。
何かありましたらご連絡ください、よろしくお願いいたします。

**Comment by mtdtks** [comment]
迅速な修正感謝します。
本日herokuで動作確認しました。問題ありません。

slackで使うのが主流な中でこのコネクターは日本人にとってとてもありがたいです。私のまわりにも普及活動しようと思いました。
本当にありがとうございました。
また機会ががありましたらよろしくお願いいたします。
今後のご活躍をお祈りしてます。

**Comment by kamera25** [comment]
@mtdtks 
正しく動いているようで良かったです。

また問題がありましたらご連絡ください。よろしくお願いいたします。
